### ISSUE TITLE
不要な記述@7.6. Project Structure Standard

### ISSUE THREAD

**Issue by shimakuray** [terasolunaorg/guideline#1409] opened 2015-11-06 08:34 UTC
## Description
[7.6. Project Structure Standard](http://terasolunaorg.github.io/guideline/5.0.1.RELEASE/ja/Appendix/ProjectStructureStandard.html)において、
* Todoが残っている（2箇所）
* [7.6.1. Simple pattern](http://terasolunaorg.github.io/guideline/5.0.1.RELEASE/ja/Appendix/ProjectStructureStandard.html#simple-pattern)は、[4.1.4.1. マルチプロジェクトの構成](http://terasolunaorg.github.io/guideline/5.0.1.RELEASE/ja/ImplementationAtEachLayer/CreateWebApplicationProject.html#createwebapplicationprojectconfigurationmulti)と似ている（1つにまとめて良いのではないか）

## Possible Solutions
TBD

## Affects Version/s
* 5.1.0.RELEASE
* 5.0.2.RELEASE
* 1.0.3.RELEASE

## Fix Version/s
- [ ] 5.2.0

## Issue Links
N/A

**Comment by ikeyat** [comment] 2016-05-24 13:37
This section was removed at #1683 since 5.2.0

**Comment by ikeyat** [comment] 2016-05-24 13:39
@btakahoshin 
Sorry, this task needs to be continued to merge something to be remained in the removed section.
So I reopened.

**Comment by btakahoshin** [comment] 2016-05-25 00:50
This task is already finish to marge in #1683 .
So please close this issue.

**Comment by ikeyat** [comment] 2016-05-25 15:30
OK, I confirmed migrated info.

**Closed by ikeyat** 2016-05-25 15:30 UTC
Labels: 5.2.0, improvement
